networks:
  timerbot:
    driver: bridge

services:
  timerbot:
    build: .
    restart: always
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - './logs:/app/logs:rw'
    depends_on:
      - redis
    networks:
      - timerbot
  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - "6379:6379"
    networks:
      - timerbot
